#Documentum Sandbox setup
version: '3.7'
services:

#Postgres DB 
  postgres:
    image: postgres:11.7
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    privileged: true
    networks:
      - dctmnetwork



  dctmcs:
    image: contentserver/centos/stateless/cs:20.2.0000.0110
    environment:
      - DOCKER_HOST=127.0.0.1
      - DATABASE_HOST=postgresdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SERVER_PORT=5432
      - SERVICE_NAME=dctmcs
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - INSTALL_OWNER=dmadmin
      - INSTALL_OWNER_PASSWORD=${INSTALL_OWNER_PASSWORD}
      - DOCBASE_NAME=dctmrepo
      - GLOBAL_REGISTRY_PASSWORD=${GLOBAL_REGISTRY_PASSWORD}
      - AEK_ALGORITHM=AES_256_CBC
      - AEK_PASSPHRASE=${AEK_PASSPHRASE}
      - AEK_NAME=
      - CONFIGURE_THUMBNAIL_SERVER=NO
      - THUMBNAIL_SERVER_PORT=8081
      - THUMBNAIL_SERVER_SSL_PORT=8443
      - EXTERNAL_DOCBROKER_PORT=1689
      - CONTENTSERVER_PORT=45326
      - APP_SERVER_PASSWORD=${APP_SERVER_PASSWORD}
      - INSTALL_OWNER_UID=1000
      - HIGH_VOLUME_SERVER_LICENSE=
      - TRUSTED_LICENSE=
      - STORAGEAWARE_LICENSE=
      - XMLSTORE_LICENSE=
      - SNAPLOCKSTORE_LICENSE=
      - RPS_LICENSE=
      - FED_RECD_SERVICE_LICENSE=
      - RECORD_MANAGER_LICENSE=
      - PRM_LICENSE=
      - DOCBASE_PASSWORD=${DOCBASE_PASSWORD}
      - INSTALLER_UI=silent
      - KEEP_TEMP_FILE=false
      - INSTALLER_DEBUG_LOG=true
      - DOCBASE_ID=453216
      - USE_EXISTING_DATABASE_ACCOUNT=
      - INDEXSPACE_NAME=DM_XCHIVE_DOCBASE
      - USE_EXISTING_AEK=false
    hostname:
      "dctmcs20"
    container_name:
      "dctmcs20"
    ports:
      - "1489:1489"
      - "1490:1490"
      - "45326:45326"
      - "45327:45327"
      - "9080:9080"
      - "9082:9082"
      - "9081:9081"
      - "9084:9084"
      - "8081:8081"
      - "8443:8443"
    volumes:
      - dctmrepo_odbc:/opt/dctm/odbc
      - dctmrepo_data:/opt/dctm/data
      - dctmrepo_dba:/opt/dctm/dba
      - dctmrepo_share:/opt/dctm/share
      - dctmrepo_dfc:/opt/dctm/config
      - dctmrepo_mdserver_conf:/opt/dctm/mdserver_conf
      - dctmrepo_mdserver_log:/opt/dctm/wildfly11.0.0/server/DctmServer_MethodServer/log
      - dctmrepo_mdserver_logs:/opt/dctm/wildfly11.0.0/server/DctmServer_MethodServer/logs
      - dctmrepo_Thumbnail_Server_conf:/opt/dctm/product/16.7/thumbsrv/conf
      - dctmrepo_Thumbnail_Server_webinf:/opt/dctm/product/16.7/thumbsrv/container/webapps/thumbsrv/WEB-INF
      - dctmrepo_xhive_storage:/opt/dctm/xhive_storage
      - dctmrepo_XhiveConnector:/opt/dctm/wildfly11.0.0/server/DctmServer_MethodServer/deployments/XhiveConnector.ear
      - dctmrepo_MigrationUtility:/opt/dctm/product/16.7/install/external_apps/MigrationUtil
    privileged: true
    depends_on:
      - postgres
    networks:
      - dctmnetwork

      

  da:
    build: 
      context: .
      dockerfile: DA.dockerfile
    environment:     
     - DA_EXT_CONF=/opt/tomcat/webapps/da/external-configurations
     - PREFERPASS=webtop
     - PRESETPASS=webtop
     #- OTDS_PROPERTIES=otds_url=<OTDS_APP_URL>::client_id=<OTDS_CLIENT_ID>::client_secret=<OTDS_CLIENT_SECRET>::redirect_uri=<DA_APP_URI>
     #- APP_PROPERTIES=application.authentication.otds_sso.enabled=false::application.authentication.otds_sso.repo_selection_page_required=false::application.authentication.otds_sso.dm_login_ticket_timeout=250::application.language.supported_locales.locale=[en_US]::application.language.default_locale=en_US
     - DFC_PROPERTIES=dfc.data.dir=/opt/tomcat/data:dfc.tokenstorage.dir=/opt/tomcat/data::dfc.tokenstorage.enable=false::dfc.docbroker.host[0]=dctmcs20::dfc.docbroker.port[0]=1489::dfc.globalregistry.repository=dctmrepo::dfc.globalregistry.username=dmadmin::dfc.globalregistry.password=admin123
    container_name:
      "dastatelesscontainer"
    ports:
     - "8080:8080"
    volumes:
     - ext-conf:/opt/tomcat/webapps/da/external-configurations    
     - dalogs:/opt/tomcat/logs
     - dacustom:/opt/tomcat/webapps/da/custom
    privileged: true
    depends_on:
      - dctmcs
    networks:
      - dctmnetwork   
    
volumes:
  dbdata:
  dctmrepo_data:
  dctmrepo_share:
  dctmrepo_dba:
  dctmrepo_dfc:
  dctmrepo_odbc:
  dctmrepo_mdserver_conf:
  dctmrepo_mdserver_log:
  dctmrepo_mdserver_logs:
  dctmrepo_Thumbnail_Server_conf:
  dctmrepo_Thumbnail_Server_webinf:
  dctmrepo_XhiveConnector:
  dctmrepo_xhive_storage:
  dctmrepo_MigrationUtility:
  ext-conf:
  dalogs:
  dacustom:


networks:
  dctmnetwork:
    driver: bridge
    name: dctmnetwork